### ISSUE TITLE
Prepare for v3

### ISSUE THREAD

**Issue by SkoebaSteve** [adopted-ember-addons/ember-launch-darkly#342]
### TODO
<hr />

- [x] Node | support `v16` and `v18` as LTS from [their release cycles](https://github.com/nodejs/release#release-schedule). Remove support for older versions.
- [x] Ember | only support LTS `3.28` and `4.4` [from their release cycles](https://emberjs.com/releases/lts/). Remove support for older versions.
- [x] Support ember-auto-import v2. Remove ember-auto-import v1 support https://github.com/adopted-ember-addons/ember-launch-darkly/pull/353
- [x] Be embroider compatible https://github.com/adopted-ember-addons/ember-launch-darkly/pull/328
- [x] Upgrade tracked-maps-and-sets(dependant on the Node and Ember upgrades) https://github.com/adopted-ember-addons/ember-launch-darkly/pull/315#issuecomment-1073786501
- [x] Replace `getUser()` with `getContext()`: https://github.com/adopted-ember-addons/ember-launch-darkly/issues/409#issuecomment-1479155306
- [x] Update readme with correct supported ember and node versions

**Comment by SkoebaSteve** [comment]
@achambers

**Comment by herzzanu** [comment]
@SkoebaSteve It looks like we can close this one.

**Comment by SkoebaSteve** [comment]
@herzzanu yes thanks for the work on this 💪 

I think we can release v3 this week, I just want to see if we want to combine it with also using LD's new version as well: https://github.com/adopted-ember-addons/ember-launch-darkly/pull/391. It has some differences in how to use the context that we would need to see if it is compatible.

WDYT?

**Comment by herzzanu** [comment]
Yes, I think 391 needs some closer investigation first. I'll have a look at it.

In the same time I started porting it to a V2 addon, maybe we can ship it in V3 🙏

**Comment by SkoebaSteve** [comment]
Just merged the v3 client of LD, looks to be non breaking: https://github.com/adopted-ember-addons/ember-launch-darkly/commit/dd1d2fc80d3e54b06b9468bf0925752d55d84979

Let's move forward with the v3 version without migrating it to a v2 addon and do that after, I think dropping old ember and node versions, auto-import v2 is enough to release a new v3 :) 

@herzzanu @achambers WDYT? If this is ok I'll update the docs as well this week before releasing

**Comment by herzzanu** [comment]
@SkoebaSteve If the new LD api is non-breaking why do we need a major release?

**Comment by SkoebaSteve** [comment]
> @SkoebaSteve Do we need a major release given the new LD api is non-breaking?

For me deprecating older ember and node versions meant it is breaking. Also just found out that there's one breaking change we need to fix 🙈 https://github.com/adopted-ember-addons/ember-launch-darkly/issues/409#issuecomment-1479155306
