### ISSUE TITLE
WIP: Prepare v4 release

### ISSUE THREAD

**Issue by SkoebaSteve** [adopted-ember-addons/ember-launch-darkly#528]
This will remove support for Ember 3.28 as it's a [long outdated LTS](https://emberjs.com/releases/lts/). I created a branch https://github.com/adopted-ember-addons/ember-launch-darkly/tree/v4-release to be used for beta releases.

```[tasklist]
### Tasks
- [x] create v4 release branch
- [ ] https://github.com/adopted-ember-addons/ember-launch-darkly/pull/486
- [ ] https://github.com/adopted-ember-addons/ember-launch-darkly/pull/498
- [ ] verify which other dependencies drop 3.28 support that can be merged
- [ ] Remove 3.28 from ember try scenarios
- [ ] Update readme
```

**Comment by RobbieTheWagner** [comment]
v4 has been released
